/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "LCD.h"
#include "GPIO_int.h"
#include "SysTick_int.h"
#include "RCC_int.h"
#include <stdint.h>
#include "EXTI_int.h"
#include "GPIO_int.h"
#include "NVIC_int.h"
#include "RCC_int.h"
#include "SPI_int.h"
#include "SysTick_int.h"
#include "SPI_Services.h"
#include "APP_Services.h"


int main(void)
{
	APP_Services_Init();

//	LCD_SetCursorWriteString(1, 1,(uint8_t*)"Mohamed TABANA");
	APP_Services_Ping_SPI_Asynch();

	while(1)
	{

		APP_Services_Periodic_Receive_Frame_Check();
	}
}
