/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "GPIO_Interface.h"
#include "RCC_Interface.h"
#include "SYSTICK_Interface.h"
PinConfig_t myPin =
{
	.Mode=OUTPUT_MSPEED,
	.Output_Type=GP_PUSH_PULL,
	.Pin_Num=PIN15,
	.Port_Num=PORTB,

};
void main(void)
{
	 GPIO_u8PinInit(&myPin);

	RCC_Set_APB2Peripheral_CLK (2 ,ENABLED);

    /* Loop forever */
	for(;;)
	{
		 GPIO_u8TogglePinStatus( PORTB,PIN15);

		 SYSTICK_u8Delay_ms	(1000);

	}
}
