/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stdint.h>
#include "STM32F446xx.h"
#include "SPI_int.h"
#include "Utils.h"
#include "GPIO_int.h"
#include "RCC_int.h"
#include "DMA_Int.h"
#include "SysTick_int.h"
#include "SPI_Services_int.h"

PinConfig_t PinSCK=
{
		.PIN_Port=PORTA,
		.PIN_Number=PIN5,
		.PIN_Type=ALTERNATE,
		.PIN_AF=AF5,
		.PIN_LCKSTS=UNLOCKED,

};
PinConfig_t PinMISO=
{
		.PIN_Port=PORTA,
		.PIN_Number=PIN6,
		.PIN_Type=ALTERNATE,
		.PIN_AF=AF5,
		.PIN_LCKSTS=UNLOCKED,

};
PinConfig_t PinMOSI=
{
		.PIN_Port=PORTA,
		.PIN_Number=PIN7,
		.PIN_Type=ALTERNATE,
		.PIN_AF=AF5,
		.PIN_LCKSTS=UNLOCKED,

};
PinConfig_t PinCS=
{
		.PIN_Port=PORTB,
		.PIN_Number=PIN6,
		.PIN_Type=ALTERNATE,
		.PIN_AF=AF5,
		.PIN_LCKSTS=UNLOCKED,

};
SPI_HandleTypeDef_t ourSPI =
{
		.SPI_ID=SPI_Channel1,
		.HWCRC_Enable=SPI_CRC_Disabled,
		.DataFrameFormat=_8_BitData,
		.SPI_Enable=SPI_Enable,
		.SPI_BaudRate=Fclk_over_2,
		.MasterSlaveSelection=SPI_Master,
		.SPI_DMARecEnable=eSPI_DMA_Rx_Disable,
		.SPI_DMATransEnable=SPI_Disable_Interrupt,
		.SwMngSlaveEnable=SPI_SW_Mng_Enabled,
		.SwSlaveSelect=SPI_SlaveNotSelected,
		.TxBufferEmptyIE=SPI_Disable_Interrupt,
		.ErrorIE=SPI_Disable_Interrupt,
		.RxBufferNotEmptyIE=SPI_Disable_Interrupt,
};
uint8_t Mydata=0;
DMA_HandleTypeDef_t ourDMA=
{
		.Init.Channel=channel_4,
		.Init.DMANumber=DMA_Number_1,
		.Init.Stream=Stream_5,
		.Init.Direction=peripheral_to_memory,
		.Init.MINC=memory_address_pointer_is_incremented_after_each_data_transfer,
		.Init.PINC=peripheral_address_pointer_is_fixed,
		.Init.CircularMode= circular_mode_enabled,
		.Init.PriorityLevel=high,
		.Init.DirectOrFIFOMode=direct_mode_enabled,
		.Init.MemoryBurst=single_transfer,
		.Init.PeripheralBurst=single_transfer,
		.Current_memory_target=current_target_memory_is_Memory_0,
		.double_buffer_mode=No_buffer_switching_at_the_end_of_transfer,
		.MemorySIZE=byte,
		.PeripheralSIZE=byte,


};
uint8_t myarr[10];
uint8_t myarr2[10]={1,2,3,4,5,6,7,8,9,10};
uint8_t recData=0;
uint8_t sendData=255;

int main(void)
{
	RCC_AHB1EnableCLK(RCC_AHB1ENR_GPIOAEN);
	RCC_AHB1EnableCLK(RCC_AHB1ENR_GPIOCEN);
	RCC_AHB1EnableCLK(RCC_AHB1ENR_GPIOBEN);

	RCC_AHB1EnableCLK(RCC_AHB1ENR_DMA1EN);
	RCC_AHB1EnableCLK(RCC_AHB1ENR_DMA2EN);

	RCC_APB1EnableCLK(RCC_APB1ENR_USART2EN);
	RCC_APB1EnableCLK(RCC_APB1ENR_SPI3EN);
	RCC_APB1EnableCLK(RCC_APB1ENR_SPI2EN);

	RCC_APB2EnableCLK(RCC_APB2ENR_SPI1EN);
	RCC_APB2EnableCLK(RCC_APB2ENR_SPI4EN);

	GPIO_u8PinInit(&PinSCK);
	GPIO_u8PinInit(&PinMISO);
	GPIO_u8PinInit(&PinMOSI);
	GPIO_u8PinInit(&PinCS);

//	UART_vInit( &ourUsart);
	SPI_vInit(&ourSPI);
	DMA_vInit( &ourDMA);
//	DMA_vStart(&ourDMA,(uint32_t)0x40004404, (uint32_t)myarr , 6);
//	DMA_vStart(&ourDMA,(uint32_t)myarr2, (uint32_t)myarr , 6);

	uint8_t data=255;

	/* Loop forever */
	while(1)
	{
//	 SPI_vSendReceive( &ourSPI, &recData, sendData--);
	 SPI_vSendDataAsynch(&ourSPI, 10,myarr2 );

//		SPI_vSendSynch( &ourSPI,data++ );
		 STK_vSetBusyWait(1000000);


	}
}
