/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
#include "RCC_int.h"
#include "GPIO_int.h"
#include "SysTick_int.h"
	RCC_AHB1EnableCLK(RCC_AHB1ENR_GPIOAEN);
	STK_vInit();


	PinConfig_t LED_PIN =
	{
			.PIN_Port=PORTA,
			.PIN_Number=PIN5,
			.PIN_Type=OUTPUT,
			.PIN_PullUpDown=NO_PULL,
			.PIN_OType=PUSH_PULL,
			.PIN_OSpeed=LOW_SPEED,
	};
	GPIO_u8PinInit( &LED_PIN);



	/* Loop forever */
	for(;;)
	{
		GPIO_vSetOutputPinValue(PORTA,PIN5,OUTPUT_HIGH);
		STK_vSetBusyWait(2000000);
		GPIO_vSetOutputPinValue(PORTA,PIN5,OUTPUT_LOW);
		STK_vSetBusyWait(2000000);

	}
}
