/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	/*
	__asm volatile ("LDR R1,=#0x20001000");
	__asm volatile ("LDR R2,=#0x20001004");
	__asm volatile ("LDR R0,[R1]");
	__asm volatile ("LDR R1,[R2]");
	__asm volatile ("add R0,R1");
	__asm volatile ("STR R0,[R2]");*/
	//__asm volatile ("MOV R0,%0"::"r"(var) );
	//__asm volatile ("MRS %0,CONTROL":"=r"(var) );


	int var1 =10;
	int var2 =20;
//	int* ptr=(int*)0x20000008;
//	int var =20;

	//task1
	__asm volatile ("MOV %0,%1":"=r"(var1):"r"(var2) );
	//task2
	//__asm volatile ("LDR %0,[%1]":"=r"(var):"r"(ptr) );

	/* Loop forever */
	for(;;);
}
