/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//===============================================================

#include <stdint.h>
#include "DMA_int.h"
#include "EXTI_int.h"
#include "GPIO_int.h"
#include "I2C_int.h"
#include "NVIC_int.h"
#include "RCC_int.h"
#include "SPI_int.h"
#include "SysTick_int.h"
#include "UART_int.h"
#include "RTC.h"
#include "SPI_Services.h"
#include "APP_Services.h"
//===============================================================


int main(void)
{

	APP_Services_Init();
	uint8_t SelectedOption=0;
	uint8_t FirstTimeFlag=0;
	while(1)
	{
		//Set Time and Date
		if (FirstTimeFlag==0)
		{
			APP_SignInScreen_Services();
			APP_WelcomeScreen_Services_Welcome();
			FirstTimeFlag=1;
		}
		//Main menu
		SelectedOption=APP_MainMenu();
		switch(SelectedOption)
		{
		case DISPLAY_TIME_DATE:
			APP_Option1_Services_Display_Time_Date();
			break;
		case SET_TIME_DATE:
			APP_Oprion2_Services_Set_Time_Data();
			break;
		case SET_ALARM:
			APP_Oprion3_Services_Set_Alarm_Display_Options();
			break;

		}
		APP_Periodically_Check_Alarms();


	}
}
