/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "NVIC_int.h"

void EXTI0_IRQHandler ()
{

	 while(1);

}
void EXTI1_IRQHandler ()
{
	 NVIC_vSetPendingFlag(EXTI0_IRQn);
	 NVIC_vEnableInterrupt(EXTI0_IRQn);
	 while(1);

}


int main(void)
{
	 NVIC_vSetPendingFlag(EXTI1_IRQn);
	 NVIC_vEnableInterrupt(EXTI1_IRQn);


    /* Loop forever */
	for(;;);
}
